/**
 * Generated by Verge3D Puzzles v.2.17.1
 * Thu Sep 24 2020 12:40:41 GMT+0300 (Moscow Standard Time)
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */

'use strict';

(function() {

// global variables/constants used by puzzles' functions
var _pGlob = {};

_pGlob.objCache = {};
_pGlob.fadeAnnotations = true;
_pGlob.objClickCallbacks = [];
_pGlob.pickedObject = '';
_pGlob.objHoverCallbacks = [];
_pGlob.hoveredObject = '';
_pGlob.objMovementInfos = {};
_pGlob.objDragOverCallbacks = [];
_pGlob.objDragOverInfoByBlock = {}
_pGlob.dragMoveOrigins = {};
_pGlob.dragScaleOrigins = {};
_pGlob.mediaElements = {};
_pGlob.loadedFiles = {};
_pGlob.loadedFile = '';
_pGlob.animMixerCallbacks = [];
_pGlob.arHitPoint = new v3d.Vector3(0, 0, 0);
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.animateParamUpdate = null;
_pGlob.openedFile = '';
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.gamepadIndex = 0;

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster();
_pGlob.intervals = {};

_pGlob.wooProductInfo = {};

var _pPhysics = {};

_pPhysics.syncList = [];

// internal info
_pPhysics.collisionData = [];

// goes to collision callback
_pPhysics.collisionInfo = {
    objectA: '',
    objectB: '',
    distance: 0,
    positionOnA: [0, 0, 0],
    positionOnB: [0, 0, 0],
    normalOnB: [0, 0, 0]
};

var PL = v3d.PL = v3d.PL || {};

// a more readable alias for PL (stands for "Puzzle Logic")
v3d.puzzles = PL;

PL.procedures = PL.procedures || {};

PL.execInitPuzzles = function() {
    var _initGlob = {};
    _initGlob.percentage = 0;
    _initGlob.output = {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        }
    }

    

    
// loadFont puzzle
function loadFont(url, family) {

    if (!url || !family)
        return;

    // register in CSS
    var elemStyle = document.createElement('style');
    elemStyle.innerHTML = '@font-face { font-family: ' + family
        + '; src: url(' + url + '); }';
    document.body.appendChild(elemStyle);

    // preload font
    var elemDiv = document.createElement('div');
    elemDiv.innerHTML = 'invisible text';
    elemDiv.style.visibility = 'hidden';
    elemDiv.style.fontFamily = family;
    document.body.appendChild(elemDiv);
}




// initSettings puzzle
_initGlob.output.initOptions.fadeAnnotations = true;
_initGlob.output.initOptions.useBkgTransp = false;
_initGlob.output.initOptions.preserveDrawBuf = false;
_initGlob.output.initOptions.useCompAssets = false;
_initGlob.output.initOptions.useFullscreen = true;

loadFont('./fonts/DaysOne-Regular.ttf', 'days-one');
loadFont('./fonts/Bellefair-Regular.ttf', 'bellefair');
loadFont('./fonts/Caveat-Regular.ttf', 'caveat');
loadFont('./fonts/GreatVibes-Regular.ttf', 'great_vibes');
loadFont('./fonts/Lobster-Regular.ttf', 'lobster');

    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {
initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}

this.procedures["update_engraving"] = update_engraving;

var engraving_ao, engaving_normal;


/**
 * Retreive standard accessible textures for MeshNodeMaterial, MeshBlenderMaterial,
 * MeshStandardMaterial and MeshPhongMaterial. If "collectSameNameMats" is true
 * then all materials in the scene with the given name will be used for collecting
 * textures, otherwise will be used only the first found material (default behavior).
 */
function matGetEditableTextures(matName, collectSameNameMats) {

    var mats = [];
    if (collectSameNameMats) {
        mats = v3d.SceneUtils.getMaterialsByName(appInstance, matName);
    } else {
        var firstMat = v3d.SceneUtils.getMaterialByName(appInstance, matName);
        if (firstMat !== null) {
            mats = [firstMat];
        }
    }

    var textures = mats.reduce(function(texArray, mat) {
        var matTextures = [];
        switch (mat.type) {
            case 'MeshNodeMaterial':
                matTextures = Object.values(mat.nodeTextures);
                break;

            case 'MeshBlenderMaterial':
                matTextures = [
                    mat.map, mat.lightMap, mat.aoMap, mat.emissiveMap,
                    mat.bumpMap, mat.normalMap, mat.displacementMap,
                    mat.specularMap, mat.alphaMap, mat.envMap
                ];
                break;

            case 'MeshStandardMaterial':
                matTextures = [
                    mat.map, mat.lightMap, mat.aoMap, mat.emissiveMap,
                    mat.bumpMap, mat.normalMap, mat.displacementMap,
                    mat.roughnessMap, mat.metalnessMap, mat.alphaMap, mat.envMap
                ]
                break;

            case 'MeshPhongMaterial':
                matTextures = [
                    mat.map, mat.lightMap, mat.aoMap, mat.emissiveMap,
                    mat.bumpMap, mat.normalMap, mat.displacementMap,
                    mat.specularMap, mat.alphaMap, mat.envMap
                ];
                break;
        }

        Array.prototype.push.apply(texArray, matTextures);
        return texArray;
    }, []);

    return textures.filter(function(elem) {
        // check Texture type exactly
        return elem && (elem.constructor == v3d.Texture || elem.constructor == v3d.DataTexture);
    });
}



// replaceTexture puzzle
function replaceTexture(matName, texName, url, doCb) {

    var textures = matGetEditableTextures(matName, true).filter(function(elem) {
        return elem.name == texName;
    });

    if (!textures.length)
        return;

    if (url instanceof Promise) {
        url.then(function(response) {
           processURL(response);
        }, function(error) {});
    } else if (typeof url == 'string') {
        processURL(url);
    } else {
        return;
    }

    function processURL(url) {

        var isHDR = (url.search(/\.hdr$/) > 0);

        if (!isHDR) {
            var loader = new v3d.ImageLoader();
            loader.setCrossOrigin('Anonymous');
        } else {
            var loader = new v3d.FileLoader();
            loader.setResponseType('arraybuffer');
        }

        loader.load(url, function(image) {
            // JPEGs can't have an alpha channel, so memory can be saved by storing them as RGB.
            var isJPEG = url.search(/\.(jpg|jpeg)$/) > 0 || url.search(/^data\:imag\/jpeg/) === 0;

            textures.forEach(function(elem) {

                if (!isHDR) {
                    elem.image = image;
                } else {
                    // parse loaded HDR buffer
                    var rgbeLoader = new v3d.RGBELoader();
                    var texData = rgbeLoader._parser(image);

                    // NOTE: reset params since the texture may be converted to float
                    elem.type = v3d.UnsignedByteType;
                    elem.encoding = v3d.RGBEEncoding;

                    elem.image = {
                        data: texData.data,
                        width: texData.width,
                        height: texData.height
                    }

                    elem.magFilter = v3d.LinearFilter;
                    elem.minFilter = v3d.LinearFilter;
                    elem.generateMipmaps = false;
                    elem.isDataTexture = true;

                }

                elem.format = isJPEG ? v3d.RGBFormat : v3d.RGBAFormat;
                elem.needsUpdate = true;

                // update world material if it is using this texture
                var wMat = appInstance.worldMaterial;
                if (wMat)
                    for (var texName in wMat.nodeTextures)
                        if (wMat.nodeTextures[texName] == elem)
                            appInstance.updateEnvironment(wMat);

                doCb();
            });
        });
    }
}


// Describe this function...
function update_engraving() {
  replaceTexture('metall', 'engrave_ao', engraving_ao, function() {});
  replaceTexture('metall', 'engrave_normal', engaving_normal, function() {});
}


// utility functions envoked by the HTML puzzles
function getElements(ids, isParent) {
    var elems = [];
    if (Array.isArray(ids) && ids[0] != 'WINDOW' &&
        ids[0] != 'DOCUMENT' && ids[0] != 'BODY' && ids[0] != 'QUERYSELECTOR') {
        for (var i = 0; i < ids.length; i++)
            elems.push(getElement(ids[i], isParent));
    } else {
        elems.push(getElement(ids, isParent));
    }
    return elems;
}

function getElement(id, isParent) {
    var elem;
    if (Array.isArray(id) && id[0] == 'WINDOW') {
        if (isParent)
            elem = parent;
        else
            elem = window;
    } else if (Array.isArray(id) && id[0] == 'DOCUMENT') {
        if (isParent)
            elem = parent.document;
        else
            elem = document;
    } else if (Array.isArray(id) && id[0] == 'BODY') {
        if (isParent)
            elem = parent.document.body;
        else
            elem = document.body;
    } else if (Array.isArray(id) && id[0] == 'QUERYSELECTOR') {
        if (isParent)
            elem = parent.document.querySelector(id);
        else
            elem = document.querySelector(id);
    } else {
        if (isParent)
            elem = parent.document.getElementById(id);
        else
            elem = document.getElementById(id);
    }
    return elem;
}



// getHTMLElemAttribute puzzle
function getHTMLElemAttribute(attr, id, isParent) {
    var elem = getElement(id, isParent);
    return elem ? elem[attr]: '';
}



// textureFromText puzzle
function textureFromText(text, width, height, family, size, align, offset) {

    var canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    var ctx = canvas.getContext('2d');
    // clear color first to prevent severe pixelating
    ctx.fillStyle = 'white';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.font = size + 'px ' + family;
    ctx.fillStyle = 'black';

    var x;
    switch (align) {
    case 'CENTER':
        ctx.textAlign = 'center';
        x = width/2;
        break;
    case 'LEFT':
        ctx.textAlign = 'left';
        x = offset;
        break;
    case 'RIGHT':
        ctx.textAlign = 'right';
        x = width - offset;
        break;
    case 'FIT':
        function fit(min, max) {
            if (max - min < 1)
                return min;
            var test = min + (max - min)/2;
            ctx.font = test + 'px ' + family;
            var measured = ctx.measureText(text).width;
            return (measured > width - 2 * offset) ? fit(min, test) : fit(test, max);
        }
        size = fit(0, height);
        x = offset;
        // no fit performed
        if ((height - size) < 1) {
            ctx.textAlign = 'center';
            x = width/2;
        }
        break;
    }
    var y = height/2 + size/4;
    ctx.fillText(text, x, y);
    return canvas.toDataURL();
}



/*
    Converts a pre-loaded image to normal map, returned as new image in Data URL format.
    Parameters:
    {
        width: 256, // pixels
        height: 256, // pixels
        strength: 2.5, // 0.01 to 5
        level: 7.0, // 4 to 10
        blur: 0.0, // -32 to 32
        filter: 'Sobel', // or 'Scharr'
        invertR: false,
        invertG: false,
        invertHeight: false
    }
    Based on NormalMap Online by Christian Petry
    Source: https://github.com/cpetry/NormalMap-Online
    Live: https://cpetry.github.io/NormalMap-Online/
*/

var NORMALGEN = NORMALGEN || {};

NORMALGEN.normalCanvas = null;
NORMALGEN.renderer = null;

NORMALGEN.convert = function(heightImage, params) {

    // init renderer
	var normalCanvas = NORMALGEN.normalCanvas = NORMALGEN.normalCanvas ||
		document.createElement('canvas');
	var renderer = NORMALGEN.renderer = NORMALGEN.renderer ||
		new v3d.WebGLRenderer({ alpha: false, antialias: true, canvas: normalCanvas });
	renderer.setSize(params.width, params.height);

	// init normal map shader
	var normalShader = NORMALGEN.NormalMapShader;
	var normalUniforms = v3d.UniformsUtils.clone(normalShader.uniforms);

    // set width and height
    normalUniforms['dimensions'].value =
        [params.width, params.height, 0];

    // set strength and level
    normalUniforms['dz'].value =
        1.0 / params.strength * (1.0 + Math.pow(2.0, params.level));

    // set filter
    normalUniforms['type'].value = (params.filter == 'Sobel') ? 0 : 1;

    // set inversion flags
    normalUniforms['invertR'].value = params.invertR ? -1 : 1;
    normalUniforms['invertG'].value = params.invertG ? -1 : 1;
    normalUniforms['invertH'].value = params.invertHeight ? -1 : 1;

    // setup texture
	var heightTex		  = new v3d.Texture(heightImage);
	heightTex.minFilter   = heightTex.magFilter = v3d.NearestFilter;
	heightTex.needsUpdate = true;
	normalUniforms['tHeightMap'].value = heightTex;

    // setup material
	var normalMat = new v3d.ShaderMaterial({
		fragmentShader: normalShader.fragmentShader,
		vertexShader: normalShader.vertexShader,
		uniforms: normalUniforms
	});

    // setup mesh
	var geometry = new v3d.PlaneBufferGeometry(1, 1, 1, 1);
	var mesh = new v3d.Mesh(geometry, normalMat);
	mesh.name = 'NORMALGEN_MESH';

    // setup scene
	var scene = new v3d.Scene();
	scene.add(mesh);
	var camera = new v3d.OrthographicCamera(1/-2, 1/2, 1/2, 1/-2, 0, 1);
	var normalPass = new v3d.RenderPass(scene, camera);

	// blur passes
	var gaussianPassY = new v3d.ShaderPass(NORMALGEN.VerticalBlurShader);
	var gaussianPassX = new v3d.ShaderPass(NORMALGEN.HorizontalBlurShader);

    // set blur params
	gaussianPassY.uniforms['v'].value = params.blur / params.width / 5;
	gaussianPassX.uniforms['h'].value = params.blur / params.height / 5;

    // setup render target
	var rtParams = { minFilter: v3d.NearestFilter, magFilter: v3d.NearestFilter,
	    format: v3d.RGBAFormat, stencilBufer: false };
	var renderTarget = new v3d.WebGLRenderTarget(params.width, params.height, rtParams);

    // setup composer
	var composer = new v3d.EffectComposer(renderer, renderTarget);
	composer.setSize(params.width, params.height);
	composer.addPass(normalPass);
	composer.addPass(gaussianPassY);
	composer.addPass(gaussianPassX);

    // draw
    composer.render(1/60);

	// retrieve image
	var resultImage = normalCanvas.toDataURL();

	// clean up
	normalMat.dispose();
	scene.dispose();
	composer.dispose();
	renderer.dispose();

	return resultImage;
}


NORMALGEN.NormalMapShader = {
	uniforms: {
		'type': 		{type: '1i', value: 0},
    	'invertR': 		{type: '1f', value: 1},
    	'invertG': 		{type: '1f', value: 1},
    	'invertH': 		{type: '1f', value: 1},
    	'dz':           {type: '1f', value: 0},
    	'dimensions': 	{type: 'fv', value: [0, 0, 0]},
    	'tHeightMap': 	{type: 't', value: null }
	},

	vertexShader: [
		'precision mediump float;',
        'varying vec2 vUv;',
		'varying vec2 step;',
        'uniform vec3 dimensions;',
        'void main() {',
			'gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );',
			'step = vec2(-1.0 / dimensions.x, -1.0 / dimensions.y);', // - to switch from glsl orientation to my orientation :D
			'vUv = uv;',
		'}'
	].join('\n'),

	fragmentShader: [
		'precision mediump float;',
        'uniform vec3 dimensions;',
        'varying vec2 vUv;',
        'varying vec2 step;',
        'uniform float dz;',
        'uniform float invertR;',
        'uniform float invertG;',
        'uniform float invertH;',
        'uniform int type;',
		'uniform sampler2D tHeightMap;',

		'void main(void) {',
		'	vec2 tlv = vec2(vUv.x - step.x, vUv.y + step.y );',
		'	vec2 lv  = vec2(vUv.x - step.x, vUv.y 		   );',
		'	vec2 blv = vec2(vUv.x - step.x, vUv.y - step.y);',
		'	vec2 tv  = vec2(vUv.x 		  , vUv.y + step.y );',
		'	vec2 bv  = vec2(vUv.x 		  , vUv.y - step.y);',
		'	vec2 trv = vec2(vUv.x + step.x, vUv.y + step.y );',
		'	vec2 rv  = vec2(vUv.x + step.x, vUv.y 		   );',
		'	vec2 brv = vec2(vUv.x + step.x, vUv.y - step.y);',
		'	tlv = vec2(tlv.x >= 0.0 ? tlv.x : (1.0 + tlv.x), 	tlv.y >= 0.0	? tlv.y : (1.0  + tlv.y));',
		'	tlv = vec2(tlv.x < 1.0  ? tlv.x : (tlv.x - 1.0 ), 	tlv.y < 1.0   	? tlv.y : (tlv.y - 1.0 ));',
		'	lv  = vec2( lv.x >= 0.0 ?  lv.x : (1.0 + lv.x),  	lv.y  >= 0.0 	?  lv.y : (1.0  +  lv.y));',
		'	lv  = vec2( lv.x < 1.0  ?  lv.x : ( lv.x - 1.0 ),   lv.y  < 1.0  	?  lv.y : ( lv.y - 1.0 ));',
		'	blv = vec2(blv.x >= 0.0 ? blv.x : (1.0 + blv.x), 	blv.y >= 0.0 	? blv.y : (1.0  + blv.y));',
		'	blv = vec2(blv.x < 1.0  ? blv.x : (blv.x - 1.0 ), 	blv.y < 1.0 	? blv.y : (blv.y - 1.0 ));',
		'	tv  = vec2( tv.x >= 0.0 ?  tv.x : (1.0 + tv.x),  	tv.y  >= 0.0 	?  tv.y : (1.0  +  tv.y));',
		'	tv  = vec2( tv.x < 1.0  ?  tv.x : ( tv.x - 1.0 ),   tv.y  < 1.0 	?  tv.y : ( tv.y - 1.0 ));',
		'	bv  = vec2( bv.x >= 0.0 ?  bv.x : (1.0 + bv.x),  	bv.y  >= 0.0 	?  bv.y : (1.0  +  bv.y));',
		'	bv  = vec2( bv.x < 1.0  ?  bv.x : ( bv.x - 1.0 ),   bv.y  < 1.0 	?  bv.y : ( bv.y - 1.0 ));',
		'	trv = vec2(trv.x >= 0.0 ? trv.x : (1.0 + trv.x), 	trv.y >= 0.0 	? trv.y : (1.0  + trv.y));',
		'	trv = vec2(trv.x < 1.0  ? trv.x : (trv.x - 1.0 ), 	trv.y < 1.0   	? trv.y : (trv.y - 1.0 ));',
		'	rv  = vec2( rv.x >= 0.0 ?  rv.x : (1.0 + rv.x),  	rv.y  >= 0.0 	?  rv.y : (1.0  +  rv.y));',
		'	rv  = vec2( rv.x < 1.0  ?  rv.x : ( rv.x - 1.0 ),   rv.y  < 1.0   	?  rv.y : ( rv.y - 1.0 ));',
		'	brv = vec2(brv.x >= 0.0 ? brv.x : (1.0 + brv.x), 	brv.y >= 0.0 	? brv.y : (1.0  + brv.y));',
		'	brv = vec2(brv.x < 1.0  ? brv.x : (brv.x - 1.0 ), 	brv.y < 1.0   	? brv.y : (brv.y - 1.0 ));',
		'	float tl = abs(texture2D(tHeightMap, tlv).r);',
		'	float l  = abs(texture2D(tHeightMap, lv ).r);',
		'	float bl = abs(texture2D(tHeightMap, blv).r);',
		'	float t  = abs(texture2D(tHeightMap, tv ).r);',
		'	float b  = abs(texture2D(tHeightMap, bv ).r);',
		'	float tr = abs(texture2D(tHeightMap, trv).r);',
		'	float r  = abs(texture2D(tHeightMap, rv ).r);',
		'	float br = abs(texture2D(tHeightMap, brv).r);',
		'   float dx = 0.0, dy = 0.0;',
		'   if(type == 0){',	// Sobel
		'		dx = tl + l*2.0 + bl - tr - r*2.0 - br;',
		'		dy = tl + t*2.0 + tr - bl - b*2.0 - br;',
		'   }',
		'   else{',				// Scharr
		'		dx = tl*3.0 + l*10.0 + bl*3.0 - tr*3.0 - r*10.0 - br*3.0;',
		'		dy = tl*3.0 + t*10.0 + tr*3.0 - bl*3.0 - b*10.0 - br*3.0;',
		'   }',
		'	vec4 normal = vec4(normalize(vec3(dx * invertR * invertH * 255.0, dy * invertG * invertH * 255.0, dz)), texture2D(tHeightMap, vUv).a);',
		'	gl_FragColor = vec4(normal.xy * 0.5 + 0.5, normal.zw);',
		'}'
	].join('\n')
};


NORMALGEN.HorizontalBlurShader = {

	uniforms: {

		'tDiffuse': { type: 't', value: null },
		'h':        { type: 'f', value: 3.0 / 512.0 }

	},

	vertexShader: [

		'varying vec2 vUv;',

		'void main() {',

			'vUv = uv;',
			'gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );',

		'}'

	].join('\n'),

	fragmentShader: [

		'uniform sampler2D tDiffuse;',
		'uniform float h;',

		'varying vec2 vUv;',

		'void main() {',

			'vec4 sum = vec4( 0.0 );',
			'float lef4 = vUv.x - 4.0 * h;',
			'float lef3 = vUv.x - 3.0 * h;',
			'float lef2 = vUv.x - 2.0 * h;',
			'float lef1 = vUv.x - 1.0 * h;',
			'float rig1 = vUv.x + 1.0 * h;',
			'float rig2 = vUv.x + 2.0 * h;',
			'float rig3 = vUv.x + 3.0 * h;',
			'float rig4 = vUv.x + 4.0 * h;',

			'lef4 = lef4 >= 0.0 ? lef4 : (1.0 + lef4);',
			'lef4 = lef4 < 1.0  ? lef4 : (lef4 - 1.0 );',
			'lef3 = lef3 >= 0.0 ? lef3 : (1.0 + lef3);',
			'lef3 = lef3 < 1.0  ? lef3 : (lef3 - 1.0 );',
			'lef2 = lef2 >= 0.0 ? lef2 : (1.0 + lef2);',
			'lef2 = lef2 < 1.0  ? lef2 : (lef2 - 1.0 );',
			'lef1 = lef1 >= 0.0 ? lef1 : (1.0 + lef1);',
			'lef1 = lef1 < 1.0  ? lef1 : (lef1 - 1.0 );',
			'rig1 = rig1 >= 0.0 ? rig1 : (1.0 + rig1);',
			'rig1 = rig1 < 1.0  ? rig1 : (rig1 - 1.0 );',
			'rig2 = rig2 >= 0.0 ? rig2 : (1.0 + rig2);',
			'rig2 = rig2 < 1.0  ? rig2 : (rig2 - 1.0 );',
			'rig3 = rig3 >= 0.0 ? rig3 : (1.0 + rig3);',
			'rig3 = rig3 < 1.0  ? rig3 : (rig3 - 1.0 );',
			'rig4 = rig4 >= 0.0 ? rig4 : (1.0 + rig4);',
			'rig4 = rig4 < 1.0  ? rig4 : (rig4 - 1.0 );',

			'sum += texture2D( tDiffuse, vec2( lef4, vUv.y ) ) * 0.051;',
			'sum += texture2D( tDiffuse, vec2( lef3, vUv.y ) ) * 0.0918;',
			'sum += texture2D( tDiffuse, vec2( lef2, vUv.y ) ) * 0.12245;',
			'sum += texture2D( tDiffuse, vec2( lef1, vUv.y ) ) * 0.1531;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, vUv.y ) ) * 0.1633;',
			'sum += texture2D( tDiffuse, vec2( rig1, vUv.y ) ) * 0.1531;',
			'sum += texture2D( tDiffuse, vec2( rig2, vUv.y ) ) * 0.12245;',
			'sum += texture2D( tDiffuse, vec2( rig3, vUv.y ) ) * 0.0918;',
			'sum += texture2D( tDiffuse, vec2( rig4, vUv.y ) ) * 0.051;',
			'if (h > 0.0){',
			'	vec4 srcValue = texture2D( tDiffuse, vec2( vUv.x, vUv.y ) );',
			'	sum = srcValue + srcValue - sum;',
			'}',
			'gl_FragColor = sum;',
			//'gl_FragColor = vec4(1,0,0,1);',

		'}'

	].join('\n')

};


NORMALGEN.VerticalBlurShader = {

	uniforms: {

		'tDiffuse': { type: 't', value: null },
		'v':        { type: 'f', value: 3.0 / 512.0 }

	},

	vertexShader: [

		'varying vec2 vUv;',

		'void main() {',

			'vUv = uv;',
			'gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );',

		'}'

	].join('\n'),

	fragmentShader: [

		'uniform sampler2D tDiffuse;',
		'uniform float v;',

		'varying vec2 vUv;',

		'void main() {',

			'vec4 sum = vec4( 0.0 );',
			'float top4 = vUv.y - 4.0 * v;',
			'float top3 = vUv.y - 3.0 * v;',
			'float top2 = vUv.y - 2.0 * v;',
			'float top1 = vUv.y - 1.0 * v;',
			'float bot1 = vUv.y + 1.0 * v;',
			'float bot2 = vUv.y + 2.0 * v;',
			'float bot3 = vUv.y + 3.0 * v;',
			'float bot4 = vUv.y + 4.0 * v;',

			'top4 = top4 >= 0.0 ? top4 : (1.0 + top4);',
			'top4 = top4 < 1.0  ? top4 : (top4 - 1.0 );',
			'top3 = top3 >= 0.0 ? top3 : (1.0 + top3);',
			'top3 = top3 < 1.0  ? top3 : (top3 - 1.0 );',
			'top2 = top2 >= 0.0 ? top2 : (1.0 + top2);',
			'top2 = top2 < 1.0  ? top2 : (top2 - 1.0 );',
			'top1 = top1 >= 0.0 ? top1 : (1.0 + top1);',
			'top1 = top1 < 1.0  ? top1 : (top1 - 1.0 );',
			'bot1 = bot1 >= 0.0 ? bot1 : (1.0 + bot1);',
			'bot1 = bot1 < 1.0  ? bot1 : (bot1 - 1.0 );',
			'bot2 = bot2 >= 0.0 ? bot2 : (1.0 + bot2);',
			'bot2 = bot2 < 1.0  ? bot2 : (bot2 - 1.0 );',
			'bot3 = bot3 >= 0.0 ? bot3 : (1.0 + bot3);',
			'bot3 = bot3 < 1.0  ? bot3 : (bot3 - 1.0 );',
			'bot4 = bot4 >= 0.0 ? bot4 : (1.0 + bot4);',
			'bot4 = bot4 < 1.0  ? bot4 : (bot4 - 1.0 );',

			'sum += texture2D( tDiffuse, vec2( vUv.x, top4 ) ) * 0.051;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, top3 ) ) * 0.0918;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, top2 ) ) * 0.12245;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, top1 ) ) * 0.1531;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, vUv.y ) ) * 0.1633;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, bot1 ) ) * 0.1531;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, bot2 ) ) * 0.12245;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, bot3 ) ) * 0.0918;',
			'sum += texture2D( tDiffuse, vec2( vUv.x, bot4 ) ) * 0.051;',
			'if (v > 0.0){',
			'	vec4 srcValue = texture2D( tDiffuse, vec2( vUv.x, vUv.y ) );',
			'	sum = srcValue + srcValue - sum;',
			'}',
			'gl_FragColor = sum;',

		'}'

	].join('\n')
};



// generateNormalMap puzzle
function generateNormalMap(srcURL, strength, level, blur, filter, invertR, invertG, invertHeight) {

    return new Promise(function(resolve, reject) {

        var heightImage = new Image();
        heightImage.src = srcURL;
        heightImage.onload = function() {

	        var output = NORMALGEN.convert(heightImage,
	            {
                    width: heightImage.width,
                    height: heightImage.height,
                    strength: strength,
                    level: level,
                    blur: blur,
                    filter: filter,
                    invertR: invertR,
                    invertG: invertG,
                    invertHeight: invertHeight
                }
            );
            resolve(output);
        };

        heightImage.onerror = function() {

            var pink = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAAC' +
                'QkWg2AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4wgNDjoFwUNXbAAAABpJREF' +
                'UKM9jfF52jYEUwMRAIhjVMKph6GgAAOxFAlM1pWHTAAAAAElFTkSuQmCC';

            resolve(pink); // return a pink image instead of failing
        };

    });

}



// eventHTMLElem puzzle
function eventHTMLElem(eventType, ids, isParent, callback) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem)
            continue;
        elem.addEventListener(eventType, callback, false);
    }
}



eventHTMLElem('click', 'add', true, function(event) {
  if (getHTMLElemAttribute('value', 'engrave_text', true).length < 12) {
    engraving_ao = textureFromText(getHTMLElemAttribute('value', 'engrave_text', true), 1024, 256, getHTMLElemAttribute('value', 'engrave_font', true), 100, 'CENTER', 5);
    engaving_normal = generateNormalMap(engraving_ao, 0.002, 0.002, -1, 'Sobel', false, false, false);
    update_engraving();
  } else {
    engraving_ao = textureFromText(getHTMLElemAttribute('value', 'engrave_text', true), 1024, 256, getHTMLElemAttribute('value', 'engrave_font', true), 100, 'FIT', 5);
    engaving_normal = generateNormalMap(engraving_ao, 0.002, 0.002, -1, 'Sobel', false, false, false);
    update_engraving();
  }
});



} // end of PL.init function

})(); // end of closure

/* ================================ end of code ============================= */
